name: Generate Release

on:
  workflow_call:
    inputs:
      SDEChangesFound:
        required: true
        type: string
      GitTag:
        required: true
        type: string
      BaselineReleaseManifestRunId:
        required: true
        type: string
      Prerelease:
        required: true
        type: string

jobs:
  GenerateManifest:
    uses: ./.github/workflows/common.release.manifests.yml
    with:
      SDEChangesFound: ${{ inputs.SDEChangesFound }}
      GitTag: ${{ inputs.GitTag }}
      ArtifactRetentionInDays: 400
      BaselineReleaseManifestRunId: ${{ inputs.BaselineReleaseManifestRunId }}
    secrets: inherit

  CreateRelease:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    needs: GenerateManifest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        shell: bash

      - name: Debugging Release
        run: |
          Write-Host "Manifest Run Id: ${{ needs.GenerateManifest.outputs.manifest_run_id }}"
        shell: pwsh

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Checkout Composite Action Repository
        uses: actions/checkout@v4
        with:
          repository: ExtremeEventSolutions/ees-compositeactions
          ref: releases/38
          path: "compositeactions"
          token: ${{ secrets.EES_COMPOSITEACTIONS_TOKEN }}

      - name: Debug Outputs from GenerateManifest
        run: |
          echo "SDE_CDK_run_id: ${{ needs.GenerateManifest.outputs.SDE_CDK_run_id }}"
          echo "sde_python_run_id: ${{ needs.GenerateManifest.outputs.sde_python_run_id }}"
          echo "sde_docker_run_id: ${{ needs.GenerateManifest.outputs.sde_docker_run_id }}"

      - name: "Download sde_cdk Artifacts"
        uses: "./compositeactions/download-artifact"
        with:
          repository: ${{ github.repository }}
          artifactname: "sde_cdk"
          localpath: "sde_cdk"
          run-id: ${{ needs.GenerateManifest.outputs.SDE_CDK_run_id }}
          token: ${{ secrets.READPACKAGE }}

      - name: "Download sde_python Artifacts"
        uses: "./compositeactions/download-artifact"
        with:
          repository: ${{ github.repository }}
          artifactname: "sde_python"
          localpath: "sde_python"
          run-id: ${{ needs.GenerateManifest.outputs.sde_python_run_id }}
          token: ${{ secrets.READPACKAGE }}

      - name: "Download sde_docker Artifacts"
        uses: "./compositeactions/download-artifact"
        with:
          repository: ${{ github.repository }}
          artifactname: "sde_docker"
          localpath: "sde_docker"
          run-id: ${{ needs.GenerateManifest.outputs.sde_docker_run_id }}
          token: ${{ secrets.READPACKAGE }}

      - name: "Zip Artifacts"
        run: |
          zip -r sde_cdk.zip sde_cdk
          zip -r sde_python.zip sde_python
          zip -r sde_docker.zip sde_docker
        shell: bash

      - name: "Create Release"
        uses: "./compositeactions/create-release"
        with:
          releaseTag: ${{ inputs.GitTag }}
          prerelease: ${{ inputs.Prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          assets: |
            sde_cdk.zip
            sde_python.zip
            sde_docker.zip
